version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fortuneplastech
      POSTGRES_USER: fortune
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
